<script>
  import { tick } from 'svelte'
  import { app } from '$lib/app.svelte.js'
  import { TALK_LABEL } from '$lib/format.js'
  import { Sparkles, Mic, ScanFace, Hand, Volume2, VolumeX, Construction } from '$lib/icons.js'
  import Message from './Message.svelte'
  import Composer from './Composer.svelte'
  import TalkOrb from './TalkOrb.svelte'

  const EXAMPLES = ['Explain recursion to me.', 'What is a derivative, intuitively?', 'How does public-key encryption work?']

  let feed = $state(null)
  let pinned = true // follow the stream unless the reader scrolled up

  const llm = $derived(app.health?.llm)
  const tail = $derived(app.messages.at(-1)?.text?.length ?? 0)
  const v = app.voice

  function onScroll() {
    if (!feed) return
    pinned = feed.scrollHeight - feed.scrollTop - feed.clientHeight < 80
  }

  $effect(() => {
    // re-run on new messages and streamed text
    void app.messages.length
    void tail
    if (!feed || !pinned) return
    tick().then(() => feed?.scrollTo({ top: feed.scrollHeight }))
  })
</script>

<main class="chat" aria-label="Conversation">
  <header class="head">
    <div class="who">
      <TalkOrb size={38} />
      <div class="who-text">
        <h1>{app.persona}</h1>
        <span class="state" data-testid="talk-state">{TALK_LABEL[app.talkState]}{#if app.talkState === 'thinking' && v.filler}<em> — “{v.filler}”</em>{/if}</span>
      </div>
      <span class="chip">{app.subject}</span>
    </div>
    <div class="meta">
      {#if v.lastLatencyMs != null}
        <span class="chip faint-chip" title="From the end of your speech to the first sound of her answer (last spoken turn)">reply in {(v.lastLatencyMs / 1000).toFixed(1)} s</span>
      {/if}
      {#if llm?.provider === 'mock'}
        <span class="chip mock" title="EH_LLM_PROVIDER=mock — answers are scripted, no LLM is called">Mock LLM · offline</span>
      {:else if llm}
        <span class="chip" title="Answers are generated by OpenAI">{llm.model}</span>
      {/if}
      {#if app.coordEnabled}
        <button class="btn sm" class:primary={app.view === 'analysis'} onclick={() => (app.view === 'analysis' ? app.closeAnalysisView() : app.openAnalysis())}
                title="Compare the utilities' public construction plans (Miami-Dade open data)" aria-pressed={app.view === 'analysis'}
                data-testid="coord-toggle"><Construction size={14} /> Coordination</button>
      {/if}
      <button class="btn sm icon" class:off={!v.speaker} onclick={() => v.setSpeaker(!v.speaker)}
              title={v.speaker ? 'Voice on — she speaks her answers (click to mute)' : 'Voice off — text only (click to unmute)'}
              aria-pressed={v.speaker} aria-label="Speak answers aloud" data-testid="speaker-toggle">
        {#if v.speaker}<Volume2 size={15} />{:else}<VolumeX size={15} />{/if}
      </button>
    </div>
  </header>

  <div class="feed" bind:this={feed} onscroll={onScroll} data-testid="feed">
    <div class="inner" class:hide-cues={!app.showCues}>
      {#if app.messages.length === 0}
        <section class="empty">
          <div class="hero-icon"><Sparkles size={22} /></div>
          <h2>What do you want to understand?</h2>
          <p>Ask {app.persona} anything — type, or turn on the microphone and just talk. She answers out loud, picks up on your facial expression, and stops the moment you interrupt her.</p>
          <div class="examples">
            {#each EXAMPLES as ex, i (ex)}
              <button class="btn" class:primary={i === 0} onclick={() => app.send(ex)} disabled={app.busy}>{ex}</button>
            {/each}
            {#if app.coordEnabled}
              <button class="btn" onclick={() => app.runAnalysis()} disabled={app.busy} data-testid="coord-example">
                <Construction size={14} /> Where do the utilities' construction plans overlap?
              </button>
            {/if}
          </div>
          <ol class="how">
            <li><Mic size={15} /><span><strong>Talk</strong> — hands-free: speech is detected on your computer; only your speech is transcribed.</span></li>
            <li><ScanFace size={15} /><span><strong>Expression</strong> — {app.local ? 'your camera is analysed on this computer' : app.viaTunnel ? "your camera is analysed on the presenter's computer" : 'camera frames are analysed by the ExtraHorizon backend'}; a short description goes into her prompt.</span></li>
            <li><Hand size={15} /><span><strong>Interrupt</strong> — speak over her (or press Esc) and she stops at once; pauses in your sentence are fine.</span></li>
          </ol>
        </section>
      {/if}

      {#each app.messages as m (m.key)}
        <Message {m} isLast={m.key === app.messages.at(-1)?.key} />
      {/each}
    </div>
  </div>

  <Composer />
</main>

<style>
  .chat { position: relative; display: flex; flex-direction: column; min-width: 0; min-height: 0; }
  .head {
    display: flex; align-items: center; justify-content: space-between; gap: 12px;
    padding: 10px 22px 10px; border-bottom: 1px solid var(--line);
    background: linear-gradient(180deg, rgb(10 16 34 / .6), rgb(10 16 34 / 0));
  }
  .who { display: flex; align-items: center; gap: 11px; min-width: 0; }
  .who-text { display: flex; flex-direction: column; min-width: 0; line-height: 1.2; }
  h1 { font-size: 16.5px; font-weight: 650; }
  .state { font-size: 12px; color: var(--muted); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 360px; }
  .state em { font-style: italic; color: var(--text-2); }
  .meta { display: flex; align-items: center; gap: 6px; }
  .faint-chip { color: var(--muted); }
  .btn.off { color: var(--faint); }
  .feed { flex: 1 1 auto; min-height: 0; overflow-y: auto; scroll-behavior: smooth; }
  .inner { max-width: var(--feed-w); margin: 0 auto; padding: 22px 22px 28px; display: flex; flex-direction: column; gap: 14px; }

  .empty { display: flex; flex-direction: column; align-items: center; text-align: center; gap: 12px; padding: 6vh 8px 10px; animation: eh-rise .6s var(--ease) both; }
  .hero-icon {
    width: 48px; height: 48px; border-radius: 14px; display: grid; place-items: center; color: #e9edff;
    background: var(--brand); box-shadow: var(--primary-rise), 0 18px 40px -16px var(--halo-violet);
  }
  .empty h2 { font-size: 24px; font-weight: 650; }
  .empty p { max-width: 540px; margin: 0; color: var(--muted); line-height: 1.6; }
  .examples { display: flex; flex-wrap: wrap; justify-content: center; gap: 8px; margin-top: 6px; }
  .how { list-style: none; margin: 18px 0 0; padding: 0; display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 10px; max-width: 740px; width: 100%; }
  .how li { display: flex; gap: 9px; align-items: flex-start; text-align: left; padding: 11px 12px; border-radius: var(--radius-sm); background: var(--plane-bg); box-shadow: var(--ring), var(--rise-1); font-size: 12.5px; color: var(--muted); line-height: 1.45; }
  .how li :global(svg) { flex: 0 0 auto; margin-top: 2px; color: var(--accent); }
  .how strong { color: var(--text-2); }
  @media (max-width: 859px) {
    .feed { overflow: visible; }
    .how { grid-template-columns: 1fr; }
    .head { padding: 10px 16px; }
    .inner { padding: 16px; }
    .state { max-width: 160px; }
  }
</style>
